FROM ubuntu:18.04

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        build-essential libgdal-dev libevent-dev libjson-c-dev \
        devscripts lintian debhelper lsb-release fakeroot
