#!/bin/bash
docker run --rm mwendler/wget --no-check-certificate -O taiwan_TIF格式.7z http://dtm.moi.gov.tw/tif/taiwan_TIF格式.7z
docker run --rm --volume $PWD:/pwd smutdose/7z x taiwan_TIF格式.7z DEMg_geoid2014_20m_20190515.tif
