steps:
- name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloudbuild.outdoorsafetylab.org/台灣本島及4離島(龜山島_綠島_蘭嶼_小琉球).7z
  - dem.7z
- name: crazymax/7zip
  entrypoint: 7za
  args:
  - x
  - dem.7z
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - $_IMAGE_NAME
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - $_IMAGE_NAME
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - $_SERVICE_NAME
  - --image=$_IMAGE_NAME
  - --region=$_REGION
  - --platform=managed
