steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=dockerhub_access_token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > dockerhub_password" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker login --username=$$USERNAME --password-stdin < dockerhub_password']
  secretEnv: ['USERNAME']
- name: python:3-slim
  entrypoint: python3
  args: ['scripts/fetch-dem.py', 'dem']
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - outdoorsafetylab/moidemd
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - tag
  - outdoorsafetylab/moidemd
  - outdoorsafetylab/moidemd:$TAG_NAME
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - outdoorsafetylab/moidemd
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - outdoorsafetylab/moidemd:$TAG_NAME
availableSecrets:
   secretManager:
   - versionName: projects/outdoorsafetylab/secrets/dockerhub_username/versions/latest
     env: USERNAME

# Downloads ~270 MB from tgos.tw and builds a 755 MiB image.
timeout: 2400s
